authors = ["<oss@fastly.com>"]
description = ""
language = "rust"
manifest_version = 3
name = "Verify if a web crawler accessing your server really is Googlebot"
service_id = "Vo7AncyczhtVsuWYbcWZL1"

[local_server.backends.origin_0]
      url = "https://dns.google.com"

[setup.backends.origin_0]
address = "dns.google.com"
port = 443
